update build

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -29,19 +29,19 @@ jobs:
     - name: Checkout code
       uses: actions/checkout@v4
       with:
-        persist-credentials: false  # Ensure that the default token is not persisted
+        persist-credentials: false
         fetch-depth: 0
         clean: true
-        token: ${{ secrets.ACTIONS_DEMO_TOKEN }}  # Use your custom secret for checkout
+        token: ${{ secrets.ACTIONS_DEMO_TOKEN }}
 
     - name: Set up JDK 17
       uses: actions/setup-java@v3
       with:
         java-version: '17'
         distribution: 'temurin'
-        server-id: github # Matches the server ID in your settings.xml
-        server-username: ${{ github.actor }} # GitHub username or actor
-        server-password: ${{ secrets.ACTIONS_DEMO_TOKEN }} # Use the custom secret for server authentication
+        server-id: github
+        server-username: ${{ github.actor }}
+        server-password: ${{ secrets.ACTIONS_DEMO_TOKEN }}
         overwrite-settings: true
 
     - name: Create Maven settings.xml
@@ -69,6 +69,13 @@ jobs:
 
     - name: Build with Maven
       run: mvn clean package
+
+    - name: Check for Artifact
+      run: |
+        if [ ! -f target/actions-demo-1.0-SNAPSHOT.jar ]; then
+          echo "Artifact not found in target directory."
+          exit 1
+        fi
 
     - name: Deploy to GitHub Packages
       run: mvn deploy -X
